version: '3' 
services:
  web:
    build: Dockerfiles/anaconda3
    env_file: .env
    volumes:
      - ./:/mediapy
    command: bash -c "mkdir -p /notebooks && 
                      /opt/conda/bin/jupyter notebook --notebook-dir=/notebooks --ip='*' --port=8888 --no-browser --NotebookApp.token=github --allow-root &&
                      conda install -y -c anaconda pymongo"
    ports:
      - 8888:8888
      - 5000:5000
    depends_on:
      - mongo
    links:
      - mongo:mongo
  mongo:
    build: Dockerfiles/mongo
    volumes:
      - ./.data/mongo:/data/db
    ports:
      - 27017:27017
