version: '2' 
services:
  web:
    build: Dockerfiles/anaconda
    env_file: .env
    ports:
      - 5000:5000
    volumes:
      - ./:/mediapy
    depends_on:
      - mongo
      - jupyter
    links:
      - mongo
      - jupyter

  jupyter:
    build: Dockerfiles/anaconda
    env_file: .env
    ports:
      - "8888:8888"
    volumes:
      - ./:/mediapy
    command: bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888
     --no-browser --allow-root --NotebookApp.token=22f5b"

  mongo:
    build: Dockerfiles/mongo
    volumes:
      - ./.data/mongo:/data/db
    ports:
      - 27017:27017
